meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php
=> fixed property bug

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/IDL_ResultList/GoogleShopping.php, src/ResultField/GoogleShopping.php
=> ADD key mutator

meta/documents/changelog_de.md, meta/documents/changelog_en.md, src/Generator/GoogleShopping.php, src/IDL_ResultList/GoogleShopping.php, src/ResultField/GoogleShopping.php
=> Release v1.0.6

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/Helper/PropertyHelper.php
FIX description evaluation by property
=> RELEASE v1.0.8

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Helper/StockHelper.php
=> added instance checks

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php
=> fixed instantiation

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/Helper/PriceHelper.php, src/ResultField/GoogleShopping.php
@plentymarkets/team-multichannel-koboldmaki 
@hschwab
=> 1.0.12 fix multilingual text and base price

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/ResultField/GoogleShopping.php
=> added the barcode mutator

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Helper/PropertyHelper.php, src/ResultField/GoogleShopping.php
=> properties will now have the right language

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/ResultField/GoogleShopping.php
=> RELEASE v1.1.0

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/Helper/PriceHelper.php
=> fixed the currency problem

meta/documents/changelog_de.md, meta/documents/changelog_en.md, meta/documents/user_guide_de.md, meta/documents/user_guide_en.md, plugin.json, resources/lang/de/logs.properties, resources/lang/en/logs.properties, src/Generator/GoogleShopping.php
=> updated user guide

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php
=> FIX shipping costs without currency

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, resources/lang/de/logs.properties, resources/lang/en/logs.properties, src/Generator/GoogleShopping.php
@plentymarkets/team-multichannel-koboldmaki 
@hschwab
=> 1.1.6 es shard size adjustment

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/Helper/AttributeHelper.php, src/ResultField/GoogleShopping.php
=> boosted the property reading perfomance

meta/documents/changelog_de.md, meta/documents/changelog_en.md, meta/documents/user_guide_de.md, meta/documents/user_guide_en.md, plugin.json, src/Generator/GoogleShopping.php, src/Helper/ImageHelper.php
@plentymarkets/team-multichannel-koboldmaki 
@hschwab
=> 1.1.8 additional image field

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php
=> changed the logs to batches of 100

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/ResultField/GoogleShopping.php
=> add image domain mutator

meta/documents/changelog_de.md, meta/documents/changelog_en.md, meta/documents/info_de.md, meta/documents/info_en.md, meta/documents/user_guide_de.md, meta/documents/user_guide_en.md, plugin.json
=> Added info tabs, updated user guide & changelogs

meta/documents/changelog_de.md, meta/documents/changelog_en.md, plugin.json, src/Generator/GoogleShopping.php, src/ResultField/GoogleShopping.php
=> laravel 5.5 update

meta/documents/changelog_de.md, meta/documents/changelog_en.md, meta/documents/user_guide_de.md, meta/documents/user_guide_en.md, plugin.json
=> Corrected broken link in the user guide

plugin.json, src/Generator/GoogleShopping.php
[AB#32331](https://dev.azure.com/plentymarkets/0af57df9-8662-4901-bb97-8e88b07ff0c9/_workitems/edit/32331)
=> fixed countable problem in google shopping elastic export

meta/documents/changelog_en.md, src/Generator/GoogleShopping.php
[AB#32331](https://dev.azure.com/plentymarkets/0af57df9-8662-4901-bb97-8e88b07ff0c9/_workitems/edit/32331)
=> removed is_countable
